### ISSUE TITLE
Z babystepping not available/not working

### ISSUE THREAD

**Issue by aweussom** [NuclearPhoenixx/Kobra_Neo#6]
Hi. I see in comments on updates that you enabled 0.01 babystepping - but I cannot find Z babystepping after a print starts?

I can adjust Z offset, but it does not appear to have any effect.

**Comment by NuclearPhoenixx** [comment]
Hi there. You should be able to select Z offset values in increments of 0.01 instead of the default resolution of 0.02. AFAIK that's exactly what this setting is supposed to do. That should also work while printing via the tune menu for example.

**Comment by aweussom** [comment]
Mmm. On stock Marlin there is a separate "Z babystepping" item in the "Tuning" menu after a print starts.
Here I can adjust Z offset in 0.01 incrementss, as you say - but my recent test seemed to have no effect on the print.
During first layer, I adjusted it from -2.99 to -2.69, which should bring the nozzle very far off the bed. No change.

So; I think one actually needs a menu item to change the Z babystepping, not just Z offset.

**Comment by aweussom** [comment]
It could be as simple as me not accessing the Z babystepping option correctly?
In stock Marlin there is an option to get to Z babystepping by rapidly clicking the button twice when print is running.

I'll download your code and check how you have it configured.

**Comment by NuclearPhoenixx** [comment]
Thanks for digging into this. The `f` is fine, it just tells the compiler the number specifically is a float.

I have enabled `DOUBLECLICK_FOR_Z_BABYSTEPPING` and recompiled the FW. Can you please test this for me and tell me if it worked for you? The `.bin` file is inside the ZIP.

[firmware.zip](https://github.com/NuclearPhoenixx/Kobra_Neo/files/15259191/firmware.zip)

Not sure where the separate menu comes from that you mentioned. I don't see any config for that here, so either it got removed entirely by Anycubic or it's a new feature in later versions of Marlin.

**Comment by aweussom** [comment]
Still No-Go. It may because the LCD is not a standard 12864 LCD - menus are different I guess.

I see that some guy with a Kingroon had the same problem, and adding  "define BABYSTEP_Z" triggered creation of the menu on his printer.

#define BABYSTEPPING
#if ENABLED(BABYSTEPPING)
**#define BABYSTEP_Z**          //gidemit added   

---

https://www.reddit.com/r/FixMyPrint/comments/1654wyz/babystepping_missing_from_tune_menu_doubleclick/

**Comment by NuclearPhoenixx** [comment]
OK, how about now? I enabled `BABYSTEP_ALWAYS_AVAILABLE` and `BABYSTEP_XY`.

[firmware.zip](https://github.com/NuclearPhoenixx/Kobra_Neo/files/15260872/firmware.zip)

**Comment by aweussom** [comment]
This has enable X/Y babystepping, but no Z babystepping.

I went looking at the source code for the TFT_COLOR_UI used by this setup (you could also #define TFT_CLASSIC_UI for a more classic menu system)

If you add
#define BABYSTEP_ZPROBE_OFFSET
at about the same place in configuration_adv.h it may work?

Looks like this option needs to be defined to enable the Z babystepping menu:

menu_tune.cpp:    #if ENABLED(**BABYSTEP_ZPROBE_OFFSET**)
menu_tune.cpp:      //SUBMENU(MSG_ZPROBE_ZOFFSET, lcd_babystep_zoffset);
menu_tune.cpp:      EDIT_ITEM(float42_52, MSG_ZPROBE_ZOFFSET, &probe.offset.z, -5.00, 5.00, []{ **lcd_babystep_zoffset**(); });
menu_tune.cpp:      SUBMENU(MSG_BABYSTEP_Z, lcd_babystep_z)

**Comment by NuclearPhoenixx** [comment]
I had the hopes that `BABYSTEP_ALWAYS_AVAILABLE` would force some kind of menu to be always visible.

> If you add
> #define BABYSTEP_ZPROBE_OFFSET
> at about the same place in configuration_adv.h it may work?

What do you mean? `BABYSTEP_ZPROBE_OFFSET` is already defined.

> Looks like this option needs to be defined to enable the Z babystepping menu:
> 
> menu_tune.cpp: #if ENABLED(**BABYSTEP_ZPROBE_OFFSET**) menu_tune.cpp: //SUBMENU(MSG_ZPROBE_ZOFFSET, lcd_babystep_zoffset); menu_tune.cpp: EDIT_ITEM(float42_52, MSG_ZPROBE_ZOFFSET, &probe.offset.z, -5.00, 5.00, []{ **lcd_babystep_zoffset**(); }); menu_tune.cpp: SUBMENU(MSG_BABYSTEP_Z, lcd_babystep_z)

I don't think so. The `EDIT_ITEM` function call just after the `SUBMENU` should already do everything the `SUBMENU` does. But just to be sure I uncommented that line to test:

[firmware.zip](https://github.com/NuclearPhoenixx/Kobra_Neo/files/15261224/firmware.zip)

**Comment by aweussom** [comment]
This gave me two menus, both named "Z offset". The topmost with three digits after period, which actually does Z babystepping (tested & verified)

The bottom menu choice has just two digits after period, and does nothing whilst printing.

![20240509_131729](https://github.com/NuclearPhoenixx/Kobra_Neo/assets/12339006/379e1392-3897-4fab-99da-369227bd7632)
![20240509_132109](https://github.com/NuclearPhoenixx/Kobra_Neo/assets/12339006/823e032c-efde-4092-b720-4c2eb42d2696)
![20240509_132240](https://github.com/NuclearPhoenixx/Kobra_Neo/assets/12339006/a1afeebd-24b0-42c3-99b1-b6497b494dac)

**Comment by NuclearPhoenixx** [comment]
Okay awesome, thanks for testing. I don't fully get what's happening here, but the changes are reflected in v1.3.6. It should work now!
